# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotebookId', models.CharField(max_length=50)),
                ('UserId', models.CharField(max_length=50)),
                ('ParentNotebookId', models.CharField(max_length=50)),
                ('Seq', models.IntegerField()),
                ('Title', models.CharField(max_length=20)),
                ('UrlTitle', models.CharField(max_length=20)),
                ('NumberNote', models.IntegerField()),
                ('IsTrash', models.BooleanField()),
                ('IsBlog', models.BooleanField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now_add=True)),
                ('IsWX', models.BooleanField()),
                ('Usn', models.IntegerField()),
                ('IsDeleted', models.BooleanField()),
                ('Subs', models.CharField(max_length=50)),
                ('Owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='NotebookOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
