# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteId', models.CharField(max_length=50)),
                ('UserId', models.CharField(max_length=50)),
                ('CreatedUserId', models.CharField(default='', max_length=50)),
                ('NotebookId', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=30)),
                ('Desc', models.TextField()),
                ('Src', models.CharField(default='', max_length=50)),
                ('ImgSrc', models.CharField(default='', max_length=50)),
                ('Tags', models.CharField(max_length=100)),
                ('IsTrash', models.BooleanField(default=False)),
                ('IsBlog', models.BooleanField(default=False)),
                ('UrlTitle', models.CharField(max_length=100)),
                ('IsRecommend', models.BooleanField(default=False)),
                ('IsTop', models.BooleanField(default=False)),
                ('HasSelfDefined', models.BooleanField(default=False)),
                ('ReadNum', models.IntegerField(default=0)),
                ('LikeNum', models.IntegerField(default=0)),
                ('CommentNum', models.IntegerField(default=0)),
                ('IsMarkdown', models.BooleanField()),
                ('AttachNum', models.IntegerField(default=0)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now_add=True)),
                ('RecommendTime', models.DateTimeField(default='0001-01-01T00:00:00Z')),
                ('PublicTime', models.DateTimeField()),
                ('UpdatedUserId', models.CharField(max_length=50)),
                ('Usn', models.IntegerField(default=11879)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsPublicShare', models.BooleanField(default=False)),
            ],
        ),
    ]
