# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0003_auto_20170421_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagId', models.CharField(max_length=50)),
                ('UserId', models.CharField(max_length=50)),
                ('Tag', models.CharField(max_length=20)),
                ('Usn', models.IntegerField()),
                ('Count', models.IntegerField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('UpdatedTime', models.DateTimeField(auto_now_add=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
