# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Content',
            field=models.TextField(default=''),
        ),
    ]
