# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0005_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Abstract',
            field=models.TextField(default=''),
        ),
    ]
