# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0006_note_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Abstract',
        ),
    ]
