# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0007_remove_note_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Abstract',
            field=models.TextField(default=''),
        ),
    ]
