# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_note', '0008_note_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='NumberNote',
        ),
        migrations.AddField(
            model_name='notebook',
            name='NumberNotes',
            field=models.IntegerField(default=0),
        ),
    ]
